services: 
  app:
    image: app/image-app
    build: 
      context: ./app
      dockerfile: dockerfile
    container_name: iotWebApp
    restart: always
    depends_on: 
      - server
    ports: 
      - 8421:3000
  
  server:
    image: server/image-server
    build: 
      context: ./server
      dockerfile: dockerfile
    container_name: iotWebServer
    depends_on: 
      - database
    ports:
      - 8321:3333
     
  worker:
    image: worker/image-worker
    build: 
      context: ./worker
      dockerfile: dockerfile
    container_name: iotWorker
    command: python main.py
    depends_on:
      - database
      - broker

  database:
    image: influxdb:2.0.7
    container_name: iotDatabase
    volumes:
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
    ports:
      - 8221:8086
    #command: docker exec iotDatabase influx setup --bucket data --org users --password 11215719 --username docker --token 1LWy6GO7ZRQy0CnzzNZTA_KUhgznI4b78xWPvFyAm17H9tYEImJ8mXYqZmvVVCWG9fXwTUDABPvmIS68kBrr8g== --name db --force
    #command: influx setup --bucket data --org users --password 11215719 --username docker --token 1LWy6GO7ZRQy0CnzzNZTA_KUhgznI4b78xWPvFyAm17H9tYEImJ8mXYqZmvVVCWG9fXwTUDABPvmIS68kBrr8g== --name db --force
    privileged: true

  broker:
    image: eclipse-mosquitto
    container_name: iotBroker
    expose:
      - 1883
    volumes:
      - ./mosquitto:/mosquitto/config
    ports:
      - 8121:1883
