services: 
  app:
    image: app/image-app
    build: 
      context: ./app
      dockerfile: dockerfile
    container_name: iotWebApp
    restart: always
    depends_on: 
      - server
    ports: 
      - 8421:3000
  
  server:
    image: server/image-server
    build: 
      context: ./server
      dockerfile: dockerfile
    container_name: iotWebServer
    depends_on: 
      - database
    ports:
      - 8321:3333
     
  worker:
    image: worker/image-worker
    build: 
      context: ./worker
      dockerfile: dockerfile
    container_name: iotWorker
    depends_on:
      - database
      - broker

  database:
    image: influxdb:2.0.7
    container_name: iotDatabase
    volumes:
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
    ports:
      - 8221:8086
    privileged: true
  
  influxdb_cli:
    links:
      - database
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /Users/anaisdotis-georgiou/temp/influxdb2:/var/lib/influxdb2:rw
      - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=idalen
      - DOCKER_INFLUXDB_INIT_PASSWORD=11215719
      - DOCKER_INFLUXDB_INIT_ORG=docker
      - DOCKER_INFLUXDB_INIT_BUCKET=data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=1LWy6GO7ZRQy0CnzzNZTA_KUhgznI4b78xWPvFyAm17H9tYEImJ8mXYqZmvVVCWG9fXwTUDABPvmIS68kBrr8g==
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - database

  broker:
    image: eclipse-mosquitto
    container_name: iotBroker
    expose:
      - 1883
    volumes:
      - ./mosquitto:/mosquitto/config
    ports:
      - 8121:1883
